{{- if not .Values.externalSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-db
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | default "changeme" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-config
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryption-key: {{ .Values.config.encryptionKey | quote }}
{{- end }}
